#!/usr/bin/env python3
"""
SentinelVision - Synthetic Provenance Metadata Generator
=========================================================

VOC2012 does not provide contributor, camera sensor, or batch metadata.
This module creates a deterministic, reproducible synthetic provenance layer
for multi-contributor benchmarking and attribution analysis.

IMPORTANT:
  These fields are strictly synthetic benchmark provenance metadata generated
  by SentinelVision for SIH PS 26228 evaluation. They are NEVER claimed to be
  original attributes of PASCAL VOC2012.
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional
import numpy as np


class ProvenanceGenerator:
    """Generates reproducible synthetic contributor, source, batch, and collection metadata."""

    def __init__(
        self,
        num_contributors: int = 10,
        num_sources: int = 5,
        num_batches: int = 20,
        num_collections: int = 4,
        seed: int = 42,
    ):
        self.num_contributors = num_contributors
        self.num_sources = num_sources
        self.num_batches = num_batches
        self.num_collections = num_collections
        self.seed = seed

    def generate_provenance(
        self,
        sample_ids: List[str],
        skew_contributor: Optional[str] = None,
        skew_fraction: float = 0.0,
    ) -> Dict[str, Dict[str, Any]]:
        """
        Assigns each sample_id to a contributor, source, batch, and collection.
        Uses deterministic pseudorandom assignment seeded by self.seed.
        Optionally concentrates a subset of samples to a specific contributor (for testing skew).
        """
        rng = np.random.default_rng(self.seed)
        contributors = [f"contributor_{i+1:02d}" for i in range(self.num_contributors)]
        sources = [f"sensor_src_{i+1:02d}" for i in range(self.num_sources)]
        batches = [f"batch_{i+1:02d}" for i in range(self.num_batches)]
        collections = [f"collection_{chr(65+i)}" for i in range(self.num_collections)]

        # Map sources and batches naturally to contributors to simulate real-world submission structure
        # (e.g., contributor_01 owns batches 01-02, uses sensors 01-02)
        contributor_sources = {}
        for c in contributors:
            assigned_src_idx = rng.choice(len(sources), size=max(1, len(sources) // len(contributors) + 1), replace=True)
            contributor_sources[c] = [sources[idx] for idx in assigned_src_idx]

        provenance_records = {}

        # Default Dirichlet-style unequal contribution distribution
        weights = rng.dirichlet(np.ones(self.num_contributors) * 2.0)

        for s_id in sample_ids:
            if skew_contributor and skew_contributor in contributors and rng.random() < skew_fraction:
                chosen_contrib = skew_contributor
            else:
                chosen_contrib = rng.choice(contributors, p=weights)

            chosen_src = rng.choice(contributor_sources[chosen_contrib])
            chosen_batch = rng.choice(batches)
            chosen_coll = rng.choice(collections)

            provenance_records[s_id] = {
                "sample_id": s_id,
                "contributor_id": chosen_contrib,
                "source_id": chosen_src,
                "batch_id": chosen_batch,
                "collection_id": chosen_coll,
                "provenance_type": "SYNTHETIC_BENCHMARK_PROVENANCE_GENERATED_BY_SENTINELVISION",
            }

        return provenance_records

    def save_provenance(
        self,
        provenance_records: Dict[str, Dict[str, Any]],
        output_path: Path,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Path:
        """Saves provenance metadata JSON to disk."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        payload = {
            "provenance_disclaimer": (
                "Synthetic benchmark provenance metadata generated by SentinelVision for "
                "SIH PS 26228 evaluation. Not part of original PASCAL VOC2012."
            ),
            "generation_parameters": {
                "num_contributors": self.num_contributors,
                "num_sources": self.num_sources,
                "num_batches": self.num_batches,
                "num_collections": self.num_collections,
                "seed": self.seed,
            },
            "sample_count": len(provenance_records),
            "metadata": metadata or {},
            "provenance": provenance_records,
        }

        payload["provenance_records"] = provenance_records

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)

        return output_path


def generate_synthetic_provenance(
    sample_ids: List[str],
    num_contributors: int = 10,
    num_sources: int = 5,
    num_batches: int = 20,
    num_collections: int = 4,
    collection_id: Optional[str] = None,
    seed: int = 42,
    output_path: Optional[str] = None,
) -> Dict[str, Any]:
    """Convenience wrapper for generating and optionally saving synthetic provenance."""
    gen = ProvenanceGenerator(
        num_contributors=num_contributors,
        num_sources=num_sources,
        num_batches=num_batches,
        num_collections=num_collections,
        seed=seed,
    )
    records = gen.generate_provenance(sample_ids)
    if collection_id:
        for r in records.values():
            r["collection_id"] = collection_id

    result = {
        "provenance_disclaimer": (
            "Synthetic benchmark provenance metadata generated by SentinelVision for "
            "SIH PS 26228 evaluation. Not part of original PASCAL VOC2012."
        ),
        "provenance_records": records,
        "provenance": records,
        "sample_count": len(records),
        "seed": seed,
    }

    if output_path:
        out_p = Path(output_path)
        out_p.parent.mkdir(parents=True, exist_ok=True)
        with open(out_p, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)

    return result
