import { useCallback, useEffect, useState } from 'react';
import { FileDown, FileText, Loader2 } from 'lucide-react';
import GlassCard from '../components/GlassCard';
import { listReports, downloadGovernanceReport } from '../services/workflowApi';
import './AuditorPages.css';

/**
 * GovernanceReports — auditor-only report center (task spec §24).
 * Downloads a real PDF generated by the bridge (reportService, pdfkit).
 */
export default function GovernanceReports({ notify }) {
  const [reports, setReports] = useState([]);
  const [periodDays, setPeriodDays] = useState(30);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      setReports(await listReports());
    } catch (err) {
      notify?.(err.message, 'error');
    } finally {
      setLoading(false);
    }
  }, [notify]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  async function download() {
    setBusy(true);
    try {
      await downloadGovernanceReport(periodDays);
      notify?.(`Governance report (${periodDays}d) downloaded.`, 'success');
      await refresh();
    } catch (err) {
      notify?.(err.message, 'error');
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="anim-fade">
      <GlassCard className="rp-card">
        <div className="card-header">
          <h3>GOVERNANCE REPORTS</h3>
          <span className="hdr-meta">PDF · SYSTEM SUMMARY · QUARANTINE · LEDGER · AUDIT TRAIL</span>
        </div>
        <p>
          Generates a real governance report from live system data: totals of tests and findings,
          integrity check outcomes, quarantine decisions with reviewers, ledger transactions with
          evidence hashes, and the audit trail for the selected period. Values are sourced from the
          bridge stores — nothing is fabricated.
        </p>
        <div className="rp-actions">
          <label className="rp-period">
            <span className="qr-sub" style={{ marginBottom: 0 }}>PERIOD</span>
            <select
              className="qr-filter"
              value={periodDays}
              onChange={(e) => setPeriodDays(Number(e.target.value))}
            >
              {[1, 7, 30, 90, 365].map((d) => (
                <option key={d} value={d}>{d === 365 ? 'LAST YEAR' : `LAST ${d} DAY${d > 1 ? 'S' : ''}`}</option>
              ))}
            </select>
          </label>
          <button className="qr-act ledger" onClick={download} disabled={busy}>
            {busy ? <Loader2 size={13} className="spin" /> : <FileDown size={13} />}
            DOWNLOAD GOVERNANCE REPORT
          </button>
        </div>
      </GlassCard>

      <GlassCard style={{ marginTop: 14 }}>
        <div className="card-header">
          <h3>PREVIOUSLY GENERATED</h3>
          <span className="hdr-meta">{reports.length} REPORTS</span>
        </div>
        <div className="aud-table-wrap" style={{ maxHeight: 320 }}>
          <table className="aud-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Generated</th>
                <th>Period</th>
                <th>Auditor</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.reportId || r._id}>
                  <td className="mono">{r.reportId || r._id}</td>
                  <td className="mono">{r.generatedAt ? new Date(r.generatedAt).toLocaleString() : '—'}</td>
                  <td>{r.periodDays ? `${r.periodDays} days` : '—'}</td>
                  <td>{r.auditorName || '—'}</td>
                </tr>
              ))}
              {!loading && reports.length === 0 && (
                <tr><td colSpan={4} className="aw-empty">NO REPORTS GENERATED YET</td></tr>
              )}
              {loading && <tr><td colSpan={4} className="aw-empty">LOADING…</td></tr>}
            </tbody>
          </table>
        </div>
      </GlassCard>
    </div>
  );
}
